/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuentas;

//import static cuentas.Form_CProductos.con;
import static cuentas.HUB.Op;
import static cuentas.HUB.con;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Pawtowta
 */
public class Form_añadir extends javax.swing.JFrame {

    /**
     * Creates new form Form_añadir1
     *
     */
    
    int NFactura = 0;
    String Cliente = "" ;
    String Direccion = "" ;
    int Ruc = 0 ;
    int fecha = 0;
  static  DefaultTableModel modelo; 
   static Operaciones Op = new Operaciones();
    
    public Form_añadir() {
        initComponents();
        
        modelo =  new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Descripcion");
        modelo.addColumn("SinIGV");
        modelo.addColumn("ConIGV");
        modelo.addColumn("Total");
        this.JTable.setModel(modelo);
        JTable.getColumnModel().getColumn(2).setPreferredWidth(120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Btn_Añadir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXT_NumeroFactura = new javax.swing.JTextField();
        TXT_Cliente = new javax.swing.JTextField();
        TXT_Direccion = new javax.swing.JTextField();
        TXT_Emision = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BTN_cancelar = new javax.swing.JButton();
        BTN_Aceptar = new javax.swing.JButton();
        TXT_Ruc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Fecha Emision :");

        Btn_Añadir.setText("Añadir producto");
        Btn_Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AñadirActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente :");

        jLabel4.setText("Direccion :");

        jLabel5.setText("R.U.C :");

        TXT_NumeroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NumeroFacturaActionPerformed(evt);
            }
        });

        TXT_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_ClienteActionPerformed(evt);
            }
        });

        TXT_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_DireccionActionPerformed(evt);
            }
        });

        TXT_Emision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_EmisionActionPerformed(evt);
            }
        });

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTable);

        jLabel1.setText("Numero Factura :");

        BTN_cancelar.setText("Cancelar");
        BTN_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_cancelarActionPerformed(evt);
            }
        });

        BTN_Aceptar.setText("Aceptar");
        BTN_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Añadir)
                        .addGap(27, 27, 27)
                        .addComponent(BTN_Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TXT_Cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(TXT_NumeroFactura, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_Direccion)
                                    .addComponent(TXT_Ruc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXT_Emision, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TXT_NumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_Emision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXT_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXT_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXT_Ruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Añadir)
                    .addComponent(BTN_cancelar)
                    .addComponent(BTN_Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AñadirActionPerformed
        // TODO add your handling code here:
        //Muestra los datos de productos
        F_Añadir FA = new F_Añadir();
        FA.setVisible(true);
        //this.setVisible(false);
        
        
    }//GEN-LAST:event_Btn_AñadirActionPerformed

    private void BTN_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_cancelarActionPerformed
        // TODO add your handling code here:
        HUB hub = new HUB();
        hub.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_cancelarActionPerformed

    private void TXT_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_DireccionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXT_DireccionActionPerformed

    private void TXT_NumeroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NumeroFacturaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_TXT_NumeroFacturaActionPerformed

    private void TXT_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_ClienteActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TXT_ClienteActionPerformed

    private void TXT_EmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_EmisionActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_TXT_EmisionActionPerformed
   //static String dato = "";
    public static void Add(int data, String data1, BigDecimal Price, String Cdato, String Model, String NPi)
    {
       
        BigDecimal IGV = new BigDecimal("1.18");
        BigDecimal SinIGV = new BigDecimal("0");
        SinIGV = Price.divide(IGV, 2, RoundingMode.HALF_UP);
        BigDecimal Cam = new BigDecimal(Cdato);
        BigDecimal Mul = Cam.multiply(Price);
        //System.out.println("datas:"+Cdato);
        
      // for(int i = 0;i < Cdato.length;i++)
        //{
       // modelo.addRow(new Object[]{data,Cdato[i],data1,"S/"+Op.formato(SinIGV),"S/"+Op.formato(data2)});    
       // }
      // modelo.addRow(new Object[]{data,data1,"S/"+Op.formato(SinIGV),"S/"+Op.formato(data2)});
       modelo.addRow(new Object[]{data,Cdato,data1+" "+Model+"-"+NPi,"S/"+Op.formato(SinIGV),"S/"+Op.formato(Price),"S/"+Op.formato(Mul)});    
   
 
    }
    
    
    private void BTN_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AceptarActionPerformed
        // TODO add your handling code here:
       // modelo.addRow(new Object[]{"s","s","S/"});
     //  int w = 2;
     //  String  e  = "";
    // TXT_Cliente.setText(dato);
      // BigDecimal r = new BigDecimal ("2");
      
       //Add(2,e,r);
       
        if( !TXT_Emision.getText().equals("") && !TXT_Ruc.getText().equals("") && !TXT_NumeroFactura.getText().equals("") && !TXT_NumeroFactura.getText().equals("") &&
                !TXT_NumeroFactura.getText().equals(""))
            
        {
        Ruc = Integer.parseInt(TXT_Ruc.getText());
        fecha = Integer.parseInt(TXT_Emision.getText());
        Cliente = TXT_Cliente.getText();
        NFactura = Integer.parseInt(TXT_NumeroFactura.getText());
        Direccion = TXT_Direccion.getText();
        System.out.print("si");
        }
         else
         {
            System.out.print("no");
         }
        
        
        
         for (int i = 0; i < JTable.getRowCount(); i++) {
             int d1 = Integer.valueOf( JTable.getValueAt(i, 0).toString());
             String d2 = JTable.getValueAt(i, 1).toString();
             String d3 = JTable.getValueAt(i, 2).toString();
             int d4 = Integer.valueOf(JTable.getValueAt(i, 3).toString());
            // Date d5 = Integer.valueOf(JTable.getValueAt(i, 4).toString());
             
             int d6 = Integer.valueOf(JTable.getValueAt(i, 5).toString());
             BigDecimal d7 = Op.parse(JTable.getValueAt(i, 6).toString());
          //   BigDecimal d4 = Op.parse(JTable1.getValueAt(i, 3).toString().replaceAll("S/",""));//Reemplaza el signo soles para q no salga error en parse
             
             
            // System.out.println("convercion:"+d4);
             
         }
        
        
        
    }//GEN-LAST:event_BTN_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_añadir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Aceptar;
    private javax.swing.JButton BTN_cancelar;
    private javax.swing.JButton Btn_Añadir;
    private javax.swing.JTable JTable;
    private javax.swing.JTextField TXT_Cliente;
    private javax.swing.JTextField TXT_Direccion;
    private javax.swing.JTextField TXT_Emision;
    private javax.swing.JTextField TXT_NumeroFactura;
    private javax.swing.JTextField TXT_Ruc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
